### ISSUE TITLE
RuntimeError: Unexpected error from cudaGetDeviceCount(). error occurred

### ISSUE THREAD

**Issue by Kanazawanaoaki** [ojh6404/tracking_ros#4]
As a quick report, the following error occurred when I tried to run the program using docker.

```
$ ./run_docker -host pr1040 -mount ./launch -name track.launch     input_image:=/kinect_head/rgb/image_rect_color     mode:=prompt     model_type:=vit_t     device:=cuda:1
---
Traceback (most recent call last):
  File "/home/user/tracking_ws/src/tracking_ros/node_scripts/sam_node.py", line 301, in <module>
    node = SAMNode()
  File "/home/user/tracking_ws/src/tracking_ros/node_scripts/sam_node.py", line 21, in __init__
    self.predictor = self.sam_config.get_predictor()
  File "/home/user/tracking_ws/src/tracking_ros/node_scripts/model_config.py", line 70, in get_predictor
    model.to(device=self.device).eval()
  File "/home/user/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/home/user/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/user/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/user/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/user/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/home/user/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/user/.local/lib/python3.9/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW
100%|██████████████████████████████████████████████████| 97.8M/97.8M [00:00<00:00, 115MB/s]
Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /home/user/.cache/torch/hub/checkpoints/resnet18-5c106cde.pth
100%|██████████████████████████████████████████████████| 44.7M/44.7M [00:00<00:00, 114MB/s]
[sam_node-1] process has died [pid 110, exit code 1, cmd /home/user/tracking_ws/devel/lib/tracking_ros/sam_node.py ~input_image:=/kinect_head/rgb/image_rect_color ~input_point:=/sam_node/output/segmentation_image/screenpoint ~input_bbox:=/sam_node/output/segmentation_image/screenrectangle __name:=sam_node __log:=/home/user/.ros/log/20240114-153226_af282e38-b2a6-11ee-97d3-a571c3c52472/sam_node-1.log].
log file: /home/user/.ros/log/20240114-153226_af282e38-b2a6-11ee-97d3-a571c3c52472/sam_node-1*.log
Traceback (most recent call last):
  File "/home/user/tracking_ws/src/tracking_ros/node_scripts/cutie_node.py", line 110, in <module>
    node = CutieNode()
  File "/home/user/tracking_ws/src/tracking_ros/node_scripts/cutie_node.py", line 21, in __init__
    self.predictor = self.cutie_config.get_predictor()
  File "/home/user/tracking_ws/src/tracking_ros/node_scripts/model_config.py", line 110, in get_predictor
    cutie = CUTIE(cfg).to(self.device).eval()
  File "/home/user/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/home/user/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/user/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/user/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/home/user/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/user/.local/lib/python3.9/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW
[cutie_node-2] process has died [pid 118, exit code 1, cmd /home/user/tracking_ws/devel/lib/tracking_ros/cutie_node.py ~input_image:=/kinect_head/rgb/image_rect_color ~input_segmentation:=/sam_node/output/segmentation __name:=cutie_node __log:=/home/user/.ros/log/20240114-153226_af282e38-b2a6-11ee-97d3-a571c3c52472/cutie_node-2.log].
log file: /home/user/.ros/log/20240114-153226_af282e38-b2a6-11ee-97d3-a571c3c52472/cutie_node-2*.log
```
I think it may be due to GPU architecture or nvida driver version and CUDA version correspondence.

### My desktop PC (Error occurred)
```
$ lspci | grep -i nvidia
1c:00.0 VGA compatible controller: NVIDIA Corporation Device 2204 (rev a1)
1c:00.1 Audio device: NVIDIA Corporation Device 1aef (rev a1)
8d:00.0 VGA compatible controller: NVIDIA Corporation Device 2204 (rev a1)
8d:00.1 Audio device: NVIDIA Corporation Device 1aef (rev a1)
```
```
$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```
```
$ cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  470.223.02  Sat Oct  7 15:39:11 UTC 2023
GCC version:  gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.2) 
```

### dlbox (Error occurred)
```
$ lspci | grep -i nvidia
1c:00.0 VGA compatible controller: NVIDIA Corporation Device 2204 (rev a1)
1c:00.1 Audio device: NVIDIA Corporation Device 1aef (rev a1)
8d:00.0 VGA compatible controller: NVIDIA Corporation Device 2204 (rev a1)
8d:00.1 Audio device: NVIDIA Corporation Device 1aef (rev a1)
```

**Comment by ojh6404** [comment]
it seems your nvidia driver does not support cuda and torch version of docker env.
I tested env with nvidia-driver 535, cuda==12.1 and torch==2.1, but it also works on cuda==11.* and torch>=1.12.
you can use cuda and torch that is suitable for your environment by replacing pulling image of docker
https://github.com/ojh6404/tracking_ros/blob/84ec5794de206ec33428f7d2e8ea7d54f6863ece/Dockerfile#L1
and install proper torch by modifying this line.
https://github.com/ojh6404/tracking_ros/blob/84ec5794de206ec33428f7d2e8ea7d54f6863ece/prepare.sh#L6

**Comment by Kanazawanaoaki** [comment]
Thank you very much!
I did the following as you suggested and the error no longer occurs.
~https://github.com/Kanazawanaoaki/tracking_ros/commit/be8bfba88989eb747d12caad0697f4ff8f05411d~
https://github.com/Kanazawanaoaki/tracking_ros/commit/f6dc7b32fe0f477bd14b9141d71b34255d68b3fe
